export default {
  en: {
    translation: {
      active: 'active',
      'add-task': 'Insert a task',
      all: 'all',
      author: 'Author',
      complete: 'complete',
      'edit-task': 'Edit task',
      'filter-task': 'Filter template',
      'required-fields-not-filled': 'You must fill in the required fields',
      'is-completed': 'Is Completed',
      login: 'Login',
      'login-username': 'Name',
      'login-password': 'Password',
      'login-enter': 'Enter',
      'login-wrong-credentials': 'Wrong username or password',
      'login-unknown-username': 'Unknown username',
      'no-tasks': 'There are no tasks',
      'remove-task': 'Remove',
      'task-id': 'ID',
      'task-name': 'Title',
      'task-name-en': 'Title (english)',
      'task-description': 'Description',
      'task-submit': 'Submit Task',
      title: 'Add Task',
      'view-task': 'View task',
    },
  },
  'en-US': {
    translation: {
      active: 'active',
      'add-task': 'Insert a task',
      all: 'all',
      author: 'Author',
      complete: 'complete',
      'edit-task': 'Edit task',
      'filter-task': 'Filter template',
      'required-fields-not-filled': 'You must fill in the required fields',
      'is-completed': 'Is Completed',
      login: 'Login',
      'login-username': 'Name',
      'login-password': 'Password',
      'login-enter': 'Enter',
      'login-wrong-credentials': 'Wrong username or password',
      'login-unknown-username': 'Unknown username',
      'no-tasks': 'There are no tasks',
      'remove-task': 'Remove',
      'task-id': 'ID',
      'task-name': 'Title',
      'task-name-en': 'Title (english)',
      'task-description': 'Description',
      'task-submit': 'Submit Task',
      title: 'Add Task',
      'view-task': 'View task',
    },
  },
  'ru-RU': {
    translation: {
      active: 'активные',
      'add-task': 'Создание',
      all: 'все',
      author: 'Автор',
      complete: 'завершённые',
      'edit-task': 'Редактирование',
      'filter-task': 'Фильтр поиска',
      'required-fields-not-filled': 'Не заполнены обязательные поля.',
      'is-completed': 'Завершено',
      login: 'Вход',
      'login-username': 'Имя',
      'login-password': 'Пароль',
      'login-enter': 'Войти',
      'login-wrong-credentials': 'Неверное имя или пароль',
      'login-unknown-username': 'Неизвестное имя',
      'no-tasks': 'Нет задач',
      'remove-task': 'Удалить',
      'task-id': 'ID',
      'task-name': 'Название',
      'task-name-en': 'Название (англ.)',
      'task-description': 'Описание',
      'task-submit': 'Сохранить',
      title: 'Задачи Jepria!!',
      'view-task': 'Задача',
    },
  },
  ru: {
    translation: {
      'required-fields-not-filled': 'Не заполнены обязательные поля.',
      all: 'все',
      author: 'Автор',
      complete: 'завершённые',
      active: 'активные',
      'add-task': 'Создание',
      'edit-task': 'Редактирование',
      'filter-task': 'Фильтр поиска',
      login: 'Вход',
      'login-username': 'Имя',
      'login-password': 'Пароль',
      'login-enter': 'Войти',
      'login-wrong-credentials': 'Неверное имя или пароль',
      'login-unknown-username': 'Неизвестное имя',
      'no-tasks': 'Нет задач',
      'task-id': 'ID',
      'task-name': 'Название',
      'task-name-en': 'Название (англ.)',
      'task-description': 'Описание',
      'task-submit': 'Сохранить',
      'is-completed': 'Завершено',
      'remove-task': 'Удалить',
      title: 'Задачи Jepria!',
      'view-task': 'Задача',
    },
  },
};
